{{- if not .Values.agentToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lotsman-agent.agentTokenSecret" . }}
  labels:
    {{- include "lotsman-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  agent-token: {{ .Values.agentToken.value | quote }}
  {{- with .Values.config.argocd.token }}
  argocd-token: {{ . | quote }}
  {{- end }}
{{- end }}
