// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lotsman.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestKind int32

const (
	RequestKind_REQUEST_KIND_UNSPECIFIED RequestKind = 0
	RequestKind_QUERY_LOGS               RequestKind = 1
	RequestKind_QUERY_METRICS_INSTANT    RequestKind = 2
	RequestKind_QUERY_METRICS_RANGE      RequestKind = 3
	RequestKind_CHANGE_EVENTS            RequestKind = 4
	RequestKind_K8S_EVENTS               RequestKind = 5
	RequestKind_LIST_WORKLOADS           RequestKind = 6
	RequestKind_LIST_PODS                RequestKind = 7
	RequestKind_POD_LOGS                 RequestKind = 8
	RequestKind_LIST_CONFIGMAPS          RequestKind = 9
	RequestKind_GET_CONFIGMAP            RequestKind = 10
	RequestKind_LIST_SECRETS             RequestKind = 11
	RequestKind_GET_SECRET               RequestKind = 12
	RequestKind_LIST_NODES               RequestKind = 13
	RequestKind_WORKLOAD_HISTORY         RequestKind = 14
)

// Enum value maps for RequestKind.
var (
	RequestKind_name = map[int32]string{
		0:  "REQUEST_KIND_UNSPECIFIED",
		1:  "QUERY_LOGS",
		2:  "QUERY_METRICS_INSTANT",
		3:  "QUERY_METRICS_RANGE",
		4:  "CHANGE_EVENTS",
		5:  "K8S_EVENTS",
		6:  "LIST_WORKLOADS",
		7:  "LIST_PODS",
		8:  "POD_LOGS",
		9:  "LIST_CONFIGMAPS",
		10: "GET_CONFIGMAP",
		11: "LIST_SECRETS",
		12: "GET_SECRET",
		13: "LIST_NODES",
		14: "WORKLOAD_HISTORY",
	}
	RequestKind_value = map[string]int32{
		"REQUEST_KIND_UNSPECIFIED": 0,
		"QUERY_LOGS":               1,
		"QUERY_METRICS_INSTANT":    2,
		"QUERY_METRICS_RANGE":      3,
		"CHANGE_EVENTS":            4,
		"K8S_EVENTS":               5,
		"LIST_WORKLOADS":           6,
		"LIST_PODS":                7,
		"POD_LOGS":                 8,
		"LIST_CONFIGMAPS":          9,
		"GET_CONFIGMAP":            10,
		"LIST_SECRETS":             11,
		"GET_SECRET":               12,
		"LIST_NODES":               13,
		"WORKLOAD_HISTORY":         14,
	}
)

func (x RequestKind) Enum() *RequestKind {
	p := new(RequestKind)
	*p = x
	return p
}

func (x RequestKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lotsman_proto_enumTypes[0].Descriptor()
}

func (RequestKind) Type() protoreflect.EnumType {
	return &file_lotsman_proto_enumTypes[0]
}

func (x RequestKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestKind.Descriptor instead.
func (RequestKind) EnumDescriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Result
	//	*AgentMessage_Event
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_lotsman_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *QueryResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // sent once on connect (enrollment + capabilities)
}

type AgentMessage_Result struct {
	Result *QueryResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // reply to a Query, correlated by request_id
}

type AgentMessage_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"` // pushed watch event
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Result) isAgentMessage_Payload() {}

func (*AgentMessage_Event) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`               // enrollment token (mTLS carries identity in prod)
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // "loki", "victoriametrics", "argocd", "kubernetes"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_lotsman_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded source result
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // non-empty on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_lotsman_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_lotsman_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type ControlPlaneMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlPlaneMessage_Query
	Payload       isControlPlaneMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlPlaneMessage) Reset() {
	*x = ControlPlaneMessage{}
	mi := &file_lotsman_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneMessage) ProtoMessage() {}

func (x *ControlPlaneMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneMessage.ProtoReflect.Descriptor instead.
func (*ControlPlaneMessage) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{4}
}

func (x *ControlPlaneMessage) GetPayload() isControlPlaneMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlPlaneMessage) GetQuery() *Query {
	if x != nil {
		if x, ok := x.Payload.(*ControlPlaneMessage_Query); ok {
			return x.Query
		}
	}
	return nil
}

type isControlPlaneMessage_Payload interface {
	isControlPlaneMessage_Payload()
}

type ControlPlaneMessage_Query struct {
	Query *Query `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

func (*ControlPlaneMessage_Query) isControlPlaneMessage_Payload() {}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind          RequestKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=lotsman.v1.RequestKind" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded source query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_lotsman_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{5}
}

func (x *Query) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Query) GetKind() RequestKind {
	if x != nil {
		return x.Kind
	}
	return RequestKind_REQUEST_KIND_UNSPECIFIED
}

func (x *Query) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Event is a server-pushed signal normalized to a resource + time. The signal
// field is a JSON-encoded model.Signal.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Signal        []byte                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_lotsman_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_lotsman_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_lotsman_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Event) GetSignal() []byte {
	if x != nil {
		return x.Signal
	}
	return nil
}

var File_lotsman_proto protoreflect.FileDescriptor

const file_lotsman_proto_rawDesc = "" +
	"\n" +
	"\rlotsman.proto\x12\n" +
	"lotsman.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\fAgentMessage\x12)\n" +
	"\x05hello\x18\x01 \x01(\v2\x11.lotsman.v1.HelloH\x00R\x05hello\x121\n" +
	"\x06result\x18\x02 \x01(\v2\x17.lotsman.v1.QueryResultH\x00R\x06result\x12)\n" +
	"\x05event\x18\x03 \x01(\v2\x11.lotsman.v1.EventH\x00R\x05event\x125\n" +
	"\theartbeat\x18\x04 \x01(\v2\x15.lotsman.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\x05Hello\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\\\n" +
	"\vQueryResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"7\n" +
	"\tHeartbeat\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"K\n" +
	"\x13ControlPlaneMessage\x12)\n" +
	"\x05query\x18\x01 \x01(\v2\x11.lotsman.v1.QueryH\x00R\x05queryB\t\n" +
	"\apayload\"m\n" +
	"\x05Query\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.lotsman.v1.RequestKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"9\n" +
	"\x05Event\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\fR\x06signal*\x9d\x02\n" +
	"\vRequestKind\x12\x1c\n" +
	"\x18REQUEST_KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"QUERY_LOGS\x10\x01\x12\x19\n" +
	"\x15QUERY_METRICS_INSTANT\x10\x02\x12\x17\n" +
	"\x13QUERY_METRICS_RANGE\x10\x03\x12\x11\n" +
	"\rCHANGE_EVENTS\x10\x04\x12\x0e\n" +
	"\n" +
	"K8S_EVENTS\x10\x05\x12\x12\n" +
	"\x0eLIST_WORKLOADS\x10\x06\x12\r\n" +
	"\tLIST_PODS\x10\a\x12\f\n" +
	"\bPOD_LOGS\x10\b\x12\x13\n" +
	"\x0fLIST_CONFIGMAPS\x10\t\x12\x11\n" +
	"\rGET_CONFIGMAP\x10\n" +
	"\x12\x10\n" +
	"\fLIST_SECRETS\x10\v\x12\x0e\n" +
	"\n" +
	"GET_SECRET\x10\f\x12\x0e\n" +
	"\n" +
	"LIST_NODES\x10\r2X\n" +
	"\fAgentService\x12H\n" +
	"\aConnect\x12\x18.lotsman.v1.AgentMessage\x1a\x1f.lotsman.v1.ControlPlaneMessage(\x010\x01B\"Z lotsman/internal/agentlink/pb;pbb\x06proto3"

var (
	file_lotsman_proto_rawDescOnce sync.Once
	file_lotsman_proto_rawDescData []byte
)

func file_lotsman_proto_rawDescGZIP() []byte {
	file_lotsman_proto_rawDescOnce.Do(func() {
		file_lotsman_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lotsman_proto_rawDesc), len(file_lotsman_proto_rawDesc)))
	})
	return file_lotsman_proto_rawDescData
}

var file_lotsman_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lotsman_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_lotsman_proto_goTypes = []any{
	(RequestKind)(0),              // 0: lotsman.v1.RequestKind
	(*AgentMessage)(nil),          // 1: lotsman.v1.AgentMessage
	(*Hello)(nil),                 // 2: lotsman.v1.Hello
	(*QueryResult)(nil),           // 3: lotsman.v1.QueryResult
	(*Heartbeat)(nil),             // 4: lotsman.v1.Heartbeat
	(*ControlPlaneMessage)(nil),   // 5: lotsman.v1.ControlPlaneMessage
	(*Query)(nil),                 // 6: lotsman.v1.Query
	(*Event)(nil),                 // 7: lotsman.v1.Event
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_lotsman_proto_depIdxs = []int32{
	2, // 0: lotsman.v1.AgentMessage.hello:type_name -> lotsman.v1.Hello
	3, // 1: lotsman.v1.AgentMessage.result:type_name -> lotsman.v1.QueryResult
	7, // 2: lotsman.v1.AgentMessage.event:type_name -> lotsman.v1.Event
	4, // 3: lotsman.v1.AgentMessage.heartbeat:type_name -> lotsman.v1.Heartbeat
	8, // 4: lotsman.v1.Heartbeat.at:type_name -> google.protobuf.Timestamp
	6, // 5: lotsman.v1.ControlPlaneMessage.query:type_name -> lotsman.v1.Query
	0, // 6: lotsman.v1.Query.kind:type_name -> lotsman.v1.RequestKind
	1, // 7: lotsman.v1.AgentService.Connect:input_type -> lotsman.v1.AgentMessage
	5, // 8: lotsman.v1.AgentService.Connect:output_type -> lotsman.v1.ControlPlaneMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_lotsman_proto_init() }
func file_lotsman_proto_init() {
	if File_lotsman_proto != nil {
		return
	}
	file_lotsman_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Event)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_lotsman_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlPlaneMessage_Query)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lotsman_proto_rawDesc), len(file_lotsman_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lotsman_proto_goTypes,
		DependencyIndexes: file_lotsman_proto_depIdxs,
		EnumInfos:         file_lotsman_proto_enumTypes,
		MessageInfos:      file_lotsman_proto_msgTypes,
	}.Build()
	File_lotsman_proto = out.File
	file_lotsman_proto_goTypes = nil
	file_lotsman_proto_depIdxs = nil
}
