{{- if and .Values.controlPlane.enabled .Values.controlPlane.ingress.enabled }}
{{- $fullName := include "lotsman.controlPlane.fullname" . }}
{{- $svcPort := .Values.controlPlane.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lotsman.componentLabels" (dict "root" . "component" "control-plane") | nindent 4 }}
  {{- with .Values.controlPlane.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.controlPlane.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.controlPlane.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.controlPlane.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
